name: Sonarqube Analysis

on:
  push:
    branches:
      - stage
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Sonarqube analyze
    runs-on: sonarqube-runners
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
